"""
Execution Engine

Executes implementation plans generated by the Planning Engine.

Pipeline

Planning Engine
        â”‚
        â–¼
Prompt Builder
        â”‚
        â–¼
LLM Client
        â”‚
        â–¼
Code Generator
        â”‚
        â–¼
Patch Generator
        â”‚
        â–¼
Patch Applier
        â”‚
        â–¼
Validator
        â”‚
        â–¼
Report
"""

from .engine import ExecutionEngine

__version__ = "1.0.0"

__all__ = [
    "ExecutionEngine",
]

