"""
Code Generator for the AI_OS Execution Engine.

Transforms LLM responses into code artifacts.
"""

from __future__ import annotations

from dataclasses import dataclass

from .llm_client import LLMResponse
from .models import CodePatch


@dataclass(slots=True)
class GeneratedCode:
    """Container for generated source code."""

    filename: str
    source: str
    explanation: str = ""


class CodeGenerator:
    """
    Converts normalized LLM responses into generated code objects.
    """

    def generate(
        self,
        response: LLMResponse,
        filename: str,
    ) -> GeneratedCode:
        if not response.success:
            raise RuntimeError(
                response.error or "LLM generation failed."
            )

        return GeneratedCode(
            filename=filename,
            source=response.content,
        )

    def to_patch(
        self,
        generated: GeneratedCode,
    ) -> CodePatch:
        return CodePatch(
            target_file=generated.filename,
            description="Generated by Execution Engine",
            updated=generated.source,
        )


