"""
Verification Engine V2

Provides a unified verification pipeline for validating code
generated by the Execution Engine before it is accepted.

Pipeline

Compiler
    ↓
PytestRunner
    ↓
Linter
    ↓
Formatter
    ↓
Coverage
    ↓
Security
    ↓
Benchmark
    ↓
Report
"""

from .engine import VerificationEngine

__version__ = "2.0.0"

__all__ = [
    "VerificationEngine",
]
